In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/predict-the-diabetes/train.csv
/kaggle/input/predict-the-diabetes/test.csv
/kaggle/input/predict-the-diabetes/sample_submission.csv


In [2]:
import tensorflow as tf

In [3]:
train_data = pd.read_csv("/kaggle/input/predict-the-diabetes/train.csv")
test_data = pd.read_csv("/kaggle/input/predict-the-diabetes/test.csv")

In [4]:
train_data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            8      183             64              0        0  23.3   
2            1       89             66             23       94  28.1   
3           10      115              0              0        0  35.3   
4            2      197             70             45      543  30.5   

   DiabetesPedigreeFunction  Age  Outcome  Id  
0                     0.627   50        1   0  
1                     0.672   32        1   2  
2                     0.167   21        0   3  
3                     0.134   29        0   7  
4                     0.158   53        1   8

In [5]:
y = train_data.iloc[:, -2].values

In [6]:
y[2]

0

In [7]:
X = train_data.iloc[:, 0:8].values

In [8]:
X[2]

array([ 1.   , 89.   , 66.   , 23.   , 94.   , 28.1  ,  0.167, 21.   ])

In [9]:
test_data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            1       85             66             29        0  26.6   
1            0      137             40             35      168  43.1   
2            5      116             74              0        0  25.6   
3            3       78             50             32       88  31.0   
4            8      125             96              0        0   0.0   

   DiabetesPedigreeFunction  Age  Id  
0                     0.351   31   1  
1                     2.288   33   4  
2                     0.201   30   5  
3                     0.248   26   6  
4                     0.232   54   9

In [10]:
X_test = test_data.iloc[:, 0:8].values

In [11]:
X_test[0]

array([ 1.   , 85.   , 66.   , 29.   ,  0.   , 26.6  ,  0.351, 31.   ])

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X)
X_test = sc.transform(X_test)

In [13]:
X_train[2]

array([-0.89401717, -1.01920921, -0.11176111,  0.12615886,  0.1021846 ,
       -0.56844002, -0.95428796, -1.06703643])

In [14]:
X_test[0]

array([-0.89401717, -1.14238926, -0.11176111,  0.49474838, -0.72017336,
       -0.76201868, -0.38256067, -0.19284695])

In [15]:
ann = tf.keras.models.Sequential()
ann.add(tf.keras.layers.Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 8))
ann.add(tf.keras.layers.Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
ann.fit(X_train, y, batch_size = 32, epochs = 100)

Epoch 1/100
15/15 [==============================] - 0s 3ms/step - loss: 0.6923 - accuracy: 0.6223
Epoch 2/100
15/15 [==============================] - 0s 2ms/step - loss: 0.6904 - accuracy: 0.6223
Epoch 3/100
15/15 [==============================] - 0s 2ms/step - loss: 0.6886 - accuracy: 0.6223
Epoch 4/100
15/15 [==============================] - 0s 2ms/step - loss: 0.6864 - accuracy: 0.6223
Epoch 5/100
15/15 [==============================] - 0s 2ms/step - loss: 0.6830 - accuracy: 0.6223
Epoch 6/100
15/15 [==============================] - 0s 2ms/step - loss: 0.6779 - accuracy: 0.6223
Epoch 7/100
15/15 [==============================] - 0s 2ms/step - loss: 0.6696 - accuracy: 0.6223
Epoch 8/100
15/15 [==============================] - 0s 2ms/step - loss: 0.6558 - accuracy: 0.6223
Epoch 9/100
15/15 [==============================] - 0s 2ms/step - loss: 0.6376 - accuracy: 0.6223
Epoch 10/100
15/15 [==============================] - 0s 2ms/step - loss: 0.6146 - accuracy: 0.6223
Epoch 11/

In [16]:
predictions = ann.predict(X_test)

In [17]:
predictions

array([[2.36640573e-02],
       [7.44027197e-01],
       [9.75615978e-02],
       [1.95673704e-02],
       [7.50497580e-02],
       [7.44027197e-01],
       [7.44027197e-01],
       [2.86272168e-01],
       [4.29212719e-01],
       [4.54256028e-01],
       [4.07642603e-01],
       [5.86630523e-01],
       [7.41445422e-01],
       [7.44027197e-01],
       [1.67468786e-02],
       [4.10692096e-02],
       [3.54498625e-03],
       [4.67160285e-01],
       [5.84952176e-01],
       [7.96746612e-02],
       [6.88864350e-01],
       [2.97583401e-01],
       [1.78748548e-01],
       [8.36797655e-02],
       [1.20515227e-02],
       [9.51549446e-05],
       [4.26363349e-02],
       [1.43134892e-01],
       [2.40804553e-02],
       [2.95087695e-03],
       [6.47001624e-01],
       [2.47413814e-02],
       [5.21983206e-02],
       [4.99922514e-01],
       [1.59178972e-02],
       [6.47103786e-03],
       [7.20123887e-01],
       [1.22303069e-02],
       [6.17712498e-01],
       [5.09600341e-01],


In [18]:
predictions = np.round(predictions)
predictions = predictions.astype(int)
print(predictions)

[[0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]


In [19]:
df = pd.DataFrame(predictions)
df_new = df.rename(columns={0 : 'Outcome'})

In [20]:
df_new.head()

Outcome
0        0
1        1
2        0
3        0
4        0

In [21]:
df_new = df_new.applymap(str)
df_new.dtypes
df_new.head()

Outcome
0       0
1       1
2       0
3       0
4       0

In [22]:
output = pd.DataFrame({'Id': test_data.Id, 'Outcome': df_new.Outcome})

In [23]:
print(output)

      Id Outcome
0      1       0
1      4       1
2      5       0
3      6       0
4      9       0
..   ...     ...
297  758       0
298  759       1
299  764       0
300  765       0
301  767       0

[302 rows x 2 columns]


In [24]:
output.to_csv('my_submission.csv', index=False)
print("Your submission was successfully saved!")

Your submission was successfully saved!
